server:
  port: 8084
  error:
    include-message: always


spring:
  application:
    name: ai-service


  datasource:
    url: jdbc:mysql://localhost:3306/resumeai_ai?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: resumeai-super-secret-key-change-in-production-2026

ai:
  gemini:
    api-key: "AIzaSyBl8S68PlRBdzw93jP1HSGku2EAVhaxVbs" # <- PASTE YOUR GEMINI API KEY HERE
    url: https://generativelanguage.googleapis.com/v1beta
    model: gemini-2.5-flash

services:
  auth-url: http://localhost:8081
  section-url: http://localhost:8083

quota:
  free:
    ai-calls: 5
    ats-checks: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info